
package perez;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "parcial_1_perez_web_operaciones_9", targetNamespace = "http://perez/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Parcial1PerezWebOperaciones9 {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://perez/", className = "perez.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://perez/", className = "perez.HelloResponse")
    @Action(input = "http://perez/parcial_1_perez_web_operaciones_9/helloRequest", output = "http://perez/parcial_1_perez_web_operaciones_9/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param resistencia
     * @param voltaje
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "parcial", targetNamespace = "http://perez/", className = "perez.Parcial")
    @ResponseWrapper(localName = "parcialResponse", targetNamespace = "http://perez/", className = "perez.ParcialResponse")
    @Action(input = "http://perez/parcial_1_perez_web_operaciones_9/parcialRequest", output = "http://perez/parcial_1_perez_web_operaciones_9/parcialResponse")
    public double parcial(
        @WebParam(name = "voltaje", targetNamespace = "")
        double voltaje,
        @WebParam(name = "resistencia", targetNamespace = "")
        double resistencia);

}
