
package perez;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "parcial_1_perez_web_operaciones_9", targetNamespace = "http://perez/", wsdlLocation = "http://localhost:8080/parcial_1_perez_4a/parcial_1_perez_web_operaciones_9?wsdl")
public class Parcial1PerezWebOperaciones9_Service
    extends Service
{

    private static final URL PARCIAL1PEREZWEBOPERACIONES9_WSDL_LOCATION;
    private static final WebServiceException PARCIAL1PEREZWEBOPERACIONES9_EXCEPTION;
    private static final QName PARCIAL1PEREZWEBOPERACIONES9_QNAME = new QName("http://perez/", "parcial_1_perez_web_operaciones_9");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/parcial_1_perez_4a/parcial_1_perez_web_operaciones_9?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARCIAL1PEREZWEBOPERACIONES9_WSDL_LOCATION = url;
        PARCIAL1PEREZWEBOPERACIONES9_EXCEPTION = e;
    }

    public Parcial1PerezWebOperaciones9_Service() {
        super(__getWsdlLocation(), PARCIAL1PEREZWEBOPERACIONES9_QNAME);
    }

    public Parcial1PerezWebOperaciones9_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARCIAL1PEREZWEBOPERACIONES9_QNAME, features);
    }

    public Parcial1PerezWebOperaciones9_Service(URL wsdlLocation) {
        super(wsdlLocation, PARCIAL1PEREZWEBOPERACIONES9_QNAME);
    }

    public Parcial1PerezWebOperaciones9_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARCIAL1PEREZWEBOPERACIONES9_QNAME, features);
    }

    public Parcial1PerezWebOperaciones9_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Parcial1PerezWebOperaciones9_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Parcial1PerezWebOperaciones9
     */
    @WebEndpoint(name = "parcial_1_perez_web_operaciones_9Port")
    public Parcial1PerezWebOperaciones9 getParcial1PerezWebOperaciones9Port() {
        return super.getPort(new QName("http://perez/", "parcial_1_perez_web_operaciones_9Port"), Parcial1PerezWebOperaciones9.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Parcial1PerezWebOperaciones9
     */
    @WebEndpoint(name = "parcial_1_perez_web_operaciones_9Port")
    public Parcial1PerezWebOperaciones9 getParcial1PerezWebOperaciones9Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://perez/", "parcial_1_perez_web_operaciones_9Port"), Parcial1PerezWebOperaciones9.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARCIAL1PEREZWEBOPERACIONES9_EXCEPTION!= null) {
            throw PARCIAL1PEREZWEBOPERACIONES9_EXCEPTION;
        }
        return PARCIAL1PEREZWEBOPERACIONES9_WSDL_LOCATION;
    }

}
