
package perez_recu;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "recu_perez_web_operaciones_9", targetNamespace = "http://perez_recu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecuPerezWebOperaciones9 {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://perez_recu/", className = "perez_recu.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://perez_recu/", className = "perez_recu.HelloResponse")
    @Action(input = "http://perez_recu/recu_perez_web_operaciones_9/helloRequest", output = "http://perez_recu/recu_perez_web_operaciones_9/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param densidad
     * @param volumen
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "masa", targetNamespace = "http://perez_recu/", className = "perez_recu.Masa")
    @ResponseWrapper(localName = "masaResponse", targetNamespace = "http://perez_recu/", className = "perez_recu.MasaResponse")
    @Action(input = "http://perez_recu/recu_perez_web_operaciones_9/masaRequest", output = "http://perez_recu/recu_perez_web_operaciones_9/masaResponse")
    public double masa(
        @WebParam(name = "densidad", targetNamespace = "")
        double densidad,
        @WebParam(name = "volumen", targetNamespace = "")
        double volumen);

}
